version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: dbt_test
      schema: dbt_asong
      tables:
          - name: customers
            description: One record per customer.            
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
            loaded_at_field: _etl_loaded_at
            freshness: 
              error_after:
                count: 12
                period: hour
              warn_after:
                count: 1
                period: day
            
          - name: payment
            loaded_at_field: _batched_at
            freshness:
              warn_after: {count: 12, period: hour}
              error_after: {count: 24, period: hour}